name: ecommerce_web_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  intl: any
  riverpod: ^2.6.1
  flutter_svg: ^2.0.16
  flutter_staggered_grid_view: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner:  

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/data/
    
    - assets/images/team_1_user_1.png
    - assets/images/team_1_user_2.png
    - assets/images/team_1_user_3.png
    - assets/images/about_title.png
    - assets/icons/fa_brand_1.png
    - assets/icons/fa_brand_2.png
    - assets/icons/fa_brand_3.png
    - assets/icons/fa_brand_4.png
    - assets/icons/fa_brand_5.png
    - assets/icons/fa_brand_6.png
    - assets/icons/facebook.png
    - assets/icons/instagram.png
    - assets/icons/twitter.png
    - assets/icons/youtube_header.png
    - assets/icons/twitter_header.png
    - assets/icons/instagram_header.png
    - assets/icons/facebook_header.png
    - assets/icons/email_header.png
    - assets/icons/phone_header.png
    - assets/icons/search.png
    - assets/icons/cart.png
    - assets/icons/favorite.png
    - assets/icons/user_login.png
    
    - assets/images/work_with_us.png
    - assets/images/scenic_image_with_play_button_overlay.png


    - assets/icons/
  fonts:
    - family: Raleway
      fonts:
        - asset: assets/fonts/Roboto-Black.ttf
          style: italic
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 400