name: ecommerce_web_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  intl: any
  riverpod: ^2.6.1
  flutter_svg: ^2.0.16
  flutter_rating_stars: ^1.1.0
  flutter_staggered_grid_view: ^0.7.0
  carousel_slider: ^5.0.0
  shimmer: ^3.0.0
  shared_preferences: ^2.3.3
  go_router: ^14.6.2
  flutter_i18n: ^0.36.2
  flutter_animate_on_scroll: ^0.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner:  

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/data/
    - assets/images/
    - assets/icons/
  fonts:
    - family: Raleway
      fonts:
        - asset: assets/fonts/Roboto-Black.ttf
          style: italic
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 400