import 'package:flutter/material.dart';

class AppColors {
  static const Color primaryColor = Color(0xFF23A6F0);
  static const Color secondaryColor = Color(0xFF03DAC6);
  static const Color backgroundColor = Color(0xFFF5F5F5);
  static const Color white = Color(0xFFFFFFFF);
  static const Color white200 = Color(0xFFF3F3F3);
  static const Color white300 = Color(0xFFFAFAFA);
  static const Color radiusColor = Color(0xFFECECEC);
  static const Color textColor = Color(0xFF212121);
  static const Color errorColor = Color(0xFFB00020);
  static const Color textPrimaryColor = Color(0xff252B42);
  static const Color textSecondaryColor = Color(0xff858585);
  static const Color textMediumGrayColor = Color(0xff737373);
  static const Color textBlueColor = Color(0xff23A6F0);
  static const Color textRedColor = Color(0xffE74040);
  static const Color textWhiteColor = Color(0xffFFFFFF);
  static const Color textColorGreen = Color(0xff23856D);
  static const Color textLightGray = Color(0xffBDBDBD);
  static const Color grayBackgroundColor = Color(0xffFAFAFA);
  static const Color whiteBackgroundColor = Color(0xffFFFFFF);
  static const Color primaryBlue = Color(0xff23A6F0);
  static const Color yellowStarColor = Color(0xffF3CD03);
  static const Color dividerGrayColor = Color(0xffBDBDBD);
  static const Color dividerLightGrayColor = Color(0xffECECEC);
  static const Color productColorGreen = Color(0xff2DC071);
  static const Color productColorOrange = Color(0xffE77C40);
  static const Color productColorBlack = Color(0xff252B42);
  static const Color circleButtonColor = Color(0xffE8E8E8);
  static const Color grayImageBackground = Color(0xffefeeee);
  static const Color textSecondaryColor2 = Color(0xffBDBDBD);
  static const Color textSecondaryColor3 = Color(0xff737373);
  static const Color textNumber = Color(0xff23856d);
  static const Color colorCircle = Color(0xffe77c40);
  static const Color secondaryBackgroundColor = Color(0xfffafafa);
  static const Color divider = Color(0xffe6e6e6);
  static const Color gestureDetectorColor = Color(0xFFD8D8D8);
  static const Color blueMiddle = Color(0xFF8EC2F2);
}
